### ISSUE TITLE
As a user, I want to see a summary of project milestones on the main project dashboard, so I know how many projects are on track.

### ISSUE THREAD

**Issue by tanflem** [KatPrend/USAF-Dashboard#14]
- [ ]  On track (Green)
- [ ]  Slightly off (Yellow)
- [ ]  Far off (red)
